# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class QCustomQWidget(QtWidgets.QWidget):  # QtWidgets
    def __init__(self, parent=None):
        super(QCustomQWidget, self).__init__(parent)
        self.textQVBoxLayout = QtWidgets.QVBoxLayout()  # QtWidgets
        self.textUpQLabel = QtWidgets.QLabel()  # QtWidgets
        self.textDownQLabel = QtWidgets.QLabel()  # QtWidgets
        self.textQVBoxLayout.addWidget(self.textUpQLabel)
        self.textQVBoxLayout.addWidget(self.textDownQLabel)
        self.allQHBoxLayout = QtWidgets.QHBoxLayout()  # QtWidgets
        self.iconQLabel = QtWidgets.QLabel()  # QtWidgets
        self.allQHBoxLayout.addWidget(self.iconQLabel, 0)
        self.allQHBoxLayout.addLayout(self.textQVBoxLayout, 1)
        self.textrightLabel = QtWidgets.QLabel()
        self.allQHBoxLayout.addWidget(self.textrightLabel)
        self.setLayout(self.allQHBoxLayout)
        self.textrightLabel.setMinimumSize(100,50)
        # setStyleSheet
        self.textUpQLabel.setStyleSheet('''
            color:rgba(253,253,254,255);
border-radius:5px;
text-align:left;
font: 10pt "Russo One";
        ''')
        self.textDownQLabel.setStyleSheet('''
            color:rgba(62,62,63,255);
border-radius:5px;
text-align:left;
font: 7pt "Russo One";
        ''')

        self.textrightLabel.setStyleSheet('''
        color:rgba(62,62,63,255);
border-radius:5px;
text-align:left;
font: 7pt "Russo One";
        ''')

    def setTextUp(self, text):
        self.textUpQLabel.setText(text)

    def setTextDown(self, text):
        self.textDownQLabel.setText(text)

    def setIcon(self, imagePath):
        self.iconQLabel.setPixmap(QtGui.QPixmap(imagePath).scaled(60, 60))

    def settime(self,time):
        self.textrightLabel.setText(time)

