# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import Qthread
from PyQt5 import QtCore, QtGui, QtWidgets
import playlist_page
from player_view import music_player
from Music_handle import Music_handler



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 793)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.mp = music_player()
        self.music_handle = Music_handler(self.mp)
        self.music_handle.start()
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1291, 768))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.frame.setObjectName("frame")
        self.left_frame = QtWidgets.QFrame(self.frame)
        self.left_frame.setGeometry(QtCore.QRect(0, 0, 221, 681))
        self.left_frame.setStyleSheet("#left_frame{\n"
                                      "background-color:rgba(18,19,25,255);\n"
                                      "border-right:2px solid rgba(58,59,64,255);\n"
                                      "}\n"
                                      "")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.app_label = QtWidgets.QLabel(self.left_frame)
        self.app_label.setGeometry(QtCore.QRect(20, 30, 58, 31))
        self.app_label.setStyleSheet("#app_label{\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "color:rgba(81,81,86,255);\n"
                                     "}")
        self.app_label.setObjectName("app_label")
        self.explore_button = QtWidgets.QPushButton(self.left_frame)
        self.explore_button.setGeometry(QtCore.QRect(20, 70, 171, 35))
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.explore_button.setFont(font)
        self.explore_button.setStyleSheet("#explore_button{\n"
                                          "background-color:rgba(18,19,25,255);\n"
                                          "color:rgba(112,112,115,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "\n"
                                          "}\n"
                                          "#explore_button:hover{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}\n"
                                          "\n"
                                          "#explore_button:checked{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/explore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/expole_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.explore_button.setIcon(icon)
        self.explore_button.setIconSize(QtCore.QSize(32, 32))
        self.explore_button.setCheckable(True)
        self.explore_button.setChecked(False)
        self.explore_button.setObjectName("explore_button")
        self.explore_button.clicked.connect(lambda : self.switchpage(0))
        self.suggest_button = QtWidgets.QPushButton(self.left_frame)
        self.suggest_button.setGeometry(QtCore.QRect(20, 120, 171, 35))
        self.suggest_button.setStyleSheet("#suggest_button{\n"
                                          "background-color:rgba(18,19,25,255);\n"
                                          "color:rgba(112,112,115,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "border-image: url(:/icon/explore.png);\n"
                                          "}\n"
                                          "#suggest_button:hover{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}\n"
                                          "#suggest_button:checked{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/suggest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/suggest_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.suggest_button.setIcon(icon1)
        self.suggest_button.setIconSize(QtCore.QSize(25, 32))
        self.suggest_button.setCheckable(True)
        self.suggest_button.setObjectName("suggest_button")
        self.tc_button = QtWidgets.QPushButton(self.left_frame)
        self.tc_button.setGeometry(QtCore.QRect(20, 170, 171, 35))
        self.tc_button.setStyleSheet("#tc_button{\n"
                                     "background-color:rgba(18,19,25,255);\n"
                                     "color:rgba(112,112,115,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}\n"
                                     "#tc_button:hover{\n"
                                     "background-color:rgba(58,80,251,255);\n"
                                     "color:rgba(255,255,255,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}\n"
                                     "#tc_button:checked{\n"
                                     "background-color:rgba(58,80,251,255);\n"
                                     "color:rgba(255,255,255,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/top.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/top_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tc_button.setIcon(icon2)
        self.tc_button.setIconSize(QtCore.QSize(32, 32))
        self.tc_button.setCheckable(True)
        self.tc_button.setObjectName("tc_button")
        self.ns_button = QtWidgets.QPushButton(self.left_frame)
        self.ns_button.setGeometry(QtCore.QRect(20, 220, 171, 35))
        self.ns_button.setStyleSheet("#ns_button{\n"
                                     "background-color:rgba(18,19,25,255);\n"
                                     "color:rgba(112,112,115,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}\n"
                                     "#ns_button:hover{\n"
                                     "background-color:rgba(58,80,251,255);\n"
                                     "color:rgba(255,255,255,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}\n"
                                     "#ns_button:checked{\n"
                                     "background-color:rgba(58,80,251,255);\n"
                                     "color:rgba(255,255,255,255);\n"
                                     "font-size:14px;\n"
                                     "border-radius:5px;\n"
                                     "text-align:left;\n"
                                     "font: 9pt \"Russo One\";\n"
                                     "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/music_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ns_button.setIcon(icon3)
        self.ns_button.setIconSize(QtCore.QSize(20, 32))
        self.ns_button.setCheckable(True)
        self.ns_button.setObjectName("ns_button")
        self.person_label = QtWidgets.QLabel(self.left_frame)
        self.person_label.setGeometry(QtCore.QRect(20, 280, 121, 31))
        self.person_label.setStyleSheet("#person_label{\n"
                                        "font: 9pt \"Russo One\";\n"
                                        "color:rgba(81,81,86,255);\n"
                                        "}")
        self.person_label.setObjectName("person_label")
        self.favorite_button = QtWidgets.QPushButton(self.left_frame)
        self.favorite_button.setGeometry(QtCore.QRect(20, 320, 171, 35))
        self.favorite_button.setStyleSheet("#favorite_button{\n"
                                           "background-color:rgba(18,19,25,255);\n"
                                           "color:rgba(112,112,115,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}\n"
                                           "#favorite_button:hover{\n"
                                           "background-color:rgba(58,80,251,255);\n"
                                           "color:rgba(255,255,255,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}\n"
                                           "#favorite_button:checked{\n"
                                           "background-color:rgba(58,80,251,255);\n"
                                           "color:rgba(255,255,255,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/favorite_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.favorite_button.setIcon(icon4)
        self.favorite_button.setCheckable(True)
        self.favorite_button.setObjectName("favorite_button")
        self.Albums_button = QtWidgets.QPushButton(self.left_frame)
        self.Albums_button.setGeometry(QtCore.QRect(20, 370, 171, 35))
        self.Albums_button.setStyleSheet("#Albums_button{\n"
                                         "background-color:rgba(18,19,25,255);\n"
                                         "color:rgba(112,112,115,255);\n"
                                         "font-size:14px;\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 9pt \"Russo One\";\n"
                                         "\n"
                                         "}\n"
                                         "#Albums_button:hover{\n"
                                         "background-color:rgba(58,80,251,255);\n"
                                         "color:rgba(255,255,255,255);\n"
                                         "font-size:14px;\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 9pt \"Russo One\";\n"
                                         "}\n"
                                         "#Albums_button:checked{\n"
                                         "background-color:rgba(58,80,251,255);\n"
                                         "color:rgba(255,255,255,255);\n"
                                         "font-size:14px;\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 9pt \"Russo One\";\n"
                                         "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/album.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/album_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Albums_button.setIcon(icon5)
        self.Albums_button.setIconSize(QtCore.QSize(25, 25))
        self.Albums_button.setCheckable(True)
        self.Albums_button.setObjectName("Albums_button")
        self.playlist_button = QtWidgets.QPushButton(self.left_frame)
        self.playlist_button.setGeometry(QtCore.QRect(20, 420, 171, 35))
        self.playlist_button.setStyleSheet("#playlist_button{\n"
                                           "background-color:rgba(18,19,25,255);\n"
                                           "color:rgba(112,112,115,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "\n"
                                           "}\n"
                                           "#playlist_button:hover{\n"
                                           "background-color:rgba(58,80,251,255);\n"
                                           "color:rgba(255,255,255,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}\n"
                                           "#playlist_button:checked{\n"
                                           "background-color:rgba(58,80,251,255);\n"
                                           "color:rgba(255,255,255,255);\n"
                                           "font-size:14px;\n"
                                           "border-radius:5px;\n"
                                           "text-align:left;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/playlist_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playlist_button.setIcon(icon6)
        self.playlist_button.setIconSize(QtCore.QSize(25, 25))
        self.playlist_button.setCheckable(True)
        self.playlist_button.setObjectName("playlist_button")
        self.playlist_button.clicked.connect(lambda: self.switchpage(1))
        self.gendres_button = QtWidgets.QPushButton(self.left_frame)
        self.gendres_button.setGeometry(QtCore.QRect(20, 470, 171, 35))
        self.gendres_button.setStyleSheet("#gendres_button{\n"
                                          "background-color:rgba(18,19,25,255);\n"
                                          "color:rgba(112,112,115,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "\n"
                                          "}\n"
                                          "#gendres_button:hover{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}\n"
                                          "\n"
                                          "#gendres_button:checked{\n"
                                          "background-color:rgba(58,80,251,255);\n"
                                          "color:rgba(255,255,255,255);\n"
                                          "font-size:14px;\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 9pt \"Russo One\";\n"
                                          "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/gender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/res/icon/res/icon/gender_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.gendres_button.setIcon(icon7)
        self.gendres_button.setIconSize(QtCore.QSize(25, 25))
        self.gendres_button.setCheckable(True)
        self.gendres_button.setObjectName("gendres_button")
        self.b_l_frame = QtWidgets.QFrame(self.frame)
        self.b_l_frame.setGeometry(QtCore.QRect(0, 680, 221, 91))
        self.b_l_frame.setStyleSheet("#b_l_frame{\n"
                                     "background-color:rgba(6,6,7,255);\n"
                                     "border-right:2px solid rgba(58,59,64,255);\n"
                                     "\n"
                                     "}")
        self.b_l_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b_l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b_l_frame.setObjectName("b_l_frame")
        self.previous_button = QtWidgets.QPushButton(self.b_l_frame)
        self.previous_button.clicked.connect(lambda : self.presong_event())
        self.previous_button.setGeometry(QtCore.QRect(30, 30, 31, 28))
        self.previous_button.setStyleSheet("#previous_button{\n"
                                           "background-color:rgba(6,6,7,255);\n"
                                           "border-image: url(\":/res/icon/res/icon/previous_song.png\") 0.5;\n"
                                           "color:rgba(112,112,115,255);\n"
                                           "padding:0;\n"
                                           "margin:0;\n"
                                           "border:none;\n"
                                           "}\n"
                                           "#previous_button:hover{\n"
                                           "background-color:rgba(6,6,7,255);\n"
                                           "border-image: url(\":/res/icon/res/icon/previous_song_after.png\") 0.5;\n"
                                           "color:rgba(112,112,115,255);\n"
                                           "padding:0;\n"
                                           "margin:0;\n"
                                           "border:none;\n"
                                           "}")
        self.previous_button.setText("")
        self.previous_button.setCheckable(True)
        self.previous_button.setObjectName("previous_button")
        self.play_button = QtWidgets.QPushButton(self.b_l_frame)
        self.play_button.setGeometry(QtCore.QRect(90, 30, 25, 25))
        self.play_button.setStyleSheet("#play_button{\n"
                                       "background-color:rgba(6,6,7,255);\n"
                                       "border-image: url(\":/res/icon/res/icon/play.png\") 0;\n"
                                       "color:rgba(112,112,115,255);\n"
                                       "padding:0;\n"
                                       "margin:0;\n"
                                       "border:none;\n"
                                       "}\n"
                                       "#play_button:hover{\n"
                                       "background-color:rgba(6,6,7,255);\n"
                                       "border-image: url(\":/res/icon/res/icon/play_after.png\") 0;\n"
                                       "color:rgba(112,112,115,255);\n"
                                       "padding:0;\n"
                                       "margin:0;\n"
                                       "border:none;\n"
                                       "}\n"
                                       "\n"
                                       "#play_button:checked{\n"
                                       "background-color:rgba(6,6,7,255);\n"
                                       "border-image: url(\":/res/icon/res/icon/pause_after.png\") 0;\n"
                                       "color:rgba(112,112,115,255);\n"
                                       "padding:0;\n"
                                       "margin:0;\n"
                                       "border:none;\n"
                                       "}")
        self.play_button.setText("")
        self.play_button.setCheckable(True)
        self.play_button.setChecked(False)
        self.play_button.clicked.connect(lambda :self.playevent())
        self.play_button.setObjectName("play_button")
        self.next_button = QtWidgets.QPushButton(self.b_l_frame)
        self.next_button.clicked.connect(lambda : self.nextsong_event())
        self.next_button.setGeometry(QtCore.QRect(140, 30, 31, 28))
        self.next_button.setStyleSheet("#next_button{\n"
                                       "background-color:rgba(6,6,7,255);\n"
                                       "border-image: url(\":/res/icon/res/icon/next_song.png\") 0.5;\n"
                                       "color:rgba(112,112,115,255);\n"
                                       "padding:0;\n"
                                       "margin:0;\n"
                                       "border:none;\n"
                                       "}\n"
                                       "#next_button:hover{\n"
                                       "background-color:rgba(6,6,7,255);\n"
                                       "border-image: url(\":/res/icon/res/icon/next_song_after.png\") 0.5;\n"
                                       "color:rgba(112,112,115,255);\n"
                                       "padding:0;\n"
                                       "margin:0;\n"
                                       "border:none;\n"
                                       "}")
        self.next_button.setText("")
        self.next_button.setCheckable(True)
        self.next_button.setObjectName("next_button")
        self.b_r_frame = QtWidgets.QFrame(self.frame)
        self.b_r_frame.setGeometry(QtCore.QRect(220, 680, 1071, 91))
        self.b_r_frame.setStyleSheet("#b_r_frame{\n"
                                     "background-color:rgba(6,6,7,255);\n"
                                     "}")
        self.b_r_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b_r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b_r_frame.setObjectName("b_r_frame")
        self.sound_button = QtWidgets.QPushButton(self.b_r_frame)
        self.sound_button.setGeometry(QtCore.QRect(30, 30, 25, 25))
        self.sound_button.setStyleSheet("#sound_button{\n"
                                        "background-color:rgba(6,6,7,255);\n"
                                        "border-image: url(\":/res/icon/res/icon/sound.png\") 0;\n"
                                        "color:rgba(112,112,115,255);\n"
                                        "padding:0;\n"
                                        "margin:0;\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#sound_button:hover{\n"
                                        "background-color:rgba(6,6,7,255);\n"
                                        "border-image: url(\":/res/icon/res/icon/sound_after.png\") 0;\n"
                                        "color:rgba(112,112,115,255);\n"
                                        "padding:0;\n"
                                        "margin:0;\n"
                                        "border:none;\n"
                                        "}")
        self.sound_button.setText("")
        self.sound_button.setCheckable(True)
        self.sound_button.setObjectName("sound_button")
        self.music_bar = QtWidgets.QProgressBar(self.b_r_frame)
        self.music_bar.setGeometry(QtCore.QRect(415, 45, 450, 10))
        self.music_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.music_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.music_bar.setStyleSheet("#music_bar{\n"
                                     "background-color:rgba(30,31,37,255);\n"
                                     "border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "#music_bar:chunk{\n"
                                     "background-color:rgba(57,80,250,255);\n"
                                     "border-radius: 5px;\n"
                                     "}")
        self.music_bar.setMinimum(0)
        self.music_bar.setValue(0)
        self.music_bar.setTextVisible(False)
        self.music_bar.setObjectName("music_bar")
        self.music_start_label = QtWidgets.QLabel(self.b_r_frame)
        self.music_start_label.setGeometry(QtCore.QRect(360, 40, 51, 20))
        self.music_start_label.setStyleSheet("#music_start_label{\n"
                                             "background-color:rgba(6,6,7,255);\n"
                                             "color:rgba(126,126,126,255);\n"
                                             "text-align:left;\n"
                                             "font: 10pt \"Russo One\";\n"
                                             "}")
        self.music_start_label.setObjectName("music_start_label")
        self.music_end_label = QtWidgets.QLabel(self.b_r_frame)
        self.music_end_label.setGeometry(QtCore.QRect(870, 40, 51, 20))
        self.music_end_label.setStyleSheet("#music_end_label{\n"
                                           "background-color:rgba(6,6,7,255);\n"
                                           "color:rgba(126,126,126,255);\n"
                                           "text-align:left;\n"
                                           "font: 10pt \"Russo One\";\n"
                                           "}")
        self.music_end_label.setObjectName("music_end_label")
        self.current_song_icon_label = QtWidgets.QLabel(self.b_r_frame)
        self.current_song_icon_label.setGeometry(QtCore.QRect(90, 20, 71, 51))
        self.current_song_icon_label.setObjectName("current_song_icon_label")
        self.current_song_name_label = QtWidgets.QLabel(self.b_r_frame)
        self.current_song_name_label.setGeometry(QtCore.QRect(180, 30, 111, 16))
        self.current_song_name_label.setStyleSheet("#current_song_name_label{\n"
                                                   "background-color:rgba(6,6,7,255);\n"
                                                   "color:rgba(253,253,254,255);\n"
                                                   "border-radius:5px;\n"
                                                   "text-align:left;\n"
                                                   "font: 10pt \"Russo One\";\n"
                                                   "}")
        self.current_song_name_label.setText("")
        self.current_song_name_label.setObjectName("current_song_name_label")
        self.current_song_artist_label = QtWidgets.QLabel(self.b_r_frame)
        self.current_song_artist_label.setGeometry(QtCore.QRect(180, 50, 111, 16))
        self.current_song_artist_label.setStyleSheet("#current_song_artist_label{\n"
                                                     "background-color:rgba(6,6,7,255);\n"
                                                     "color:rgba(62,62,63,255);\n"
                                                     "border-radius:5px;\n"
                                                     "text-align:left;\n"
                                                     "font: 7pt \"Russo One\";\n"
                                                     "\n"
                                                     "}")
        self.current_song_artist_label.setText("")
        self.current_song_artist_label.setObjectName("current_song_artist_label")
        self.stack = QtWidgets.QStackedWidget(self.frame)
        self.stack.setGeometry(QtCore.QRect(220, 0, 1071, 681))
        self.stack.setObjectName("stack")
        self.indexpage = QtWidgets.QWidget()
        self.indexpage.setObjectName("indexpage")
        self.right_frame = QtWidgets.QFrame(self.indexpage)
        self.right_frame.setGeometry(QtCore.QRect(0, 0, 1071, 681))
        self.right_frame.setStyleSheet("#right_frame{\n"
                                       "background-color:rgba(20,21,28,255);\n"
                                       "}")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.back_page_button = QtWidgets.QPushButton(self.right_frame)
        self.back_page_button.setGeometry(QtCore.QRect(40, 30, 20, 20))
        self.back_page_button.setStyleSheet("#back_page_button{\n"
                                            "background-color:rgba(20,21,28,255);\n"
                                            "border-image: url(\":/res/icon/res/icon/back.png\") 0.5;\n"
                                            "color:rgba(112,112,115,255);\n"
                                            "padding:0;\n"
                                            "margin:0;\n"
                                            "border:none;\n"
                                            "}\n"
                                            "#back_page_button:hover{\n"
                                            "background-color:rgba(20,21,28,255);\n"
                                            "border-image: url(\":/res/icon/res/icon/back_after.png\") 0.5;\n"
                                            "color:rgba(112,112,115,255);\n"
                                            "padding:0;\n"
                                            "margin:0;\n"
                                            "border:none;\n"
                                            "}")
        self.back_page_button.setText("")
        self.back_page_button.setCheckable(True)
        self.back_page_button.setObjectName("back_page_button")
        self.forward_page_button = QtWidgets.QPushButton(self.right_frame)
        self.forward_page_button.setGeometry(QtCore.QRect(70, 30, 20, 20))
        self.forward_page_button.setStyleSheet("#forward_page_button{\n"
                                               "background-color:rgba(20,21,28,255);\n"
                                               "border-image: url(\":/res/icon/res/icon/forward.png\") 0.5;\n"
                                               "color:rgba(112,112,115,255);\n"
                                               "padding:0;\n"
                                               "margin:0;\n"
                                               "border:none;\n"
                                               "}\n"
                                               "#forward_page_button:hover{\n"
                                               "background-color:rgba(20,21,28,255);\n"
                                               "border-image: url(\":/res/icon/res/icon/forward_next.png\") 0.5;\n"
                                               "color:rgba(112,112,115,255);\n"
                                               "padding:0;\n"
                                               "margin:0;\n"
                                               "border:none;\n"
                                               "}")
        self.forward_page_button.setText("")
        self.forward_page_button.setCheckable(True)
        self.forward_page_button.setObjectName("forward_page_button")
        self.search_lineedit = QtWidgets.QLineEdit(self.right_frame)
        self.search_lineedit.setGeometry(QtCore.QRect(190, 30, 361, 22))
        self.search_lineedit.setStyleSheet("#search_lineedit{\n"
                                           "color:rgba(97,97,102,255);\n"
                                           "background-color:rgba(20,21,28,255);\n"
                                           "border:0px;\n"
                                           "font: 9pt \"Russo One\";\n"
                                           "}")
        self.search_lineedit.setObjectName("search_lineedit")
        self.search_button = QtWidgets.QPushButton(self.right_frame)
        self.search_button.setGeometry(QtCore.QRect(160, 30, 20, 20))
        self.search_button.setStyleSheet("#search_button{\n"
                                         "background-color:rgba(20,21,28,255);\n"
                                         "border-image: url(\":/res/icon/res/icon/search.png\") 0;\n"
                                         "color:rgba(112,112,115,255);\n"
                                         "padding:0;\n"
                                         "margin:0;\n"
                                         "border:none;\n"
                                         "}\n"
                                         "#search_button:hover{\n"
                                         "background-color:rgba(20,21,28,255);\n"
                                         "border-image: url(\":/res/icon/res/icon/search_after.png\") 0;\n"
                                         "color:rgba(112,112,115,255);\n"
                                         "padding:0;\n"
                                         "margin:0;\n"
                                         "border:none;\n"
                                         "}")
        self.search_button.setText("")
        self.search_button.setObjectName("search_button")
        self.explore_new_label = QtWidgets.QLabel(self.right_frame)

        self.explore_new_label.setGeometry(QtCore.QRect(50, 80, 171, 41))
        self.explore_new_label.setStyleSheet("#explore_new_label{\n"
                                             "background-color:rgba(18,19,25,255);\n"
                                             "color:rgba(253,253,254,255);\n"
                                             "border-radius:5px;\n"
                                             "text-align:left;\n"
                                             "font: 15pt \"Russo One\";\n"
                                             "}")
        self.explore_new_label.setObjectName("explore_new_label")
        self.popular_label = QtWidgets.QLabel(self.right_frame)
        self.popular_label.setGeometry(QtCore.QRect(50, 360, 171, 41))
        self.popular_label.setStyleSheet("#popular_label{\n"
                                         "background-color:rgba(18,19,25,255);\n"
                                         "color:rgba(253,253,254,255);\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 15pt \"Russo One\";\n"
                                         "}")
        self.popular_label.setObjectName("popular_label")
        self.mood_label = QtWidgets.QLabel(self.right_frame)
        self.mood_label.setGeometry(QtCore.QRect(620, 360, 171, 41))
        self.mood_label.setStyleSheet("#mood_label{\n"
                                      "background-color:rgba(18,19,25,255);\n"
                                      "color:rgba(253,253,254,255);\n"
                                      "border-radius:5px;\n"
                                      "text-align:left;\n"
                                      "font: 15pt \"Russo One\";\n"
                                      "}")
        self.mood_label.setObjectName("mood_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.right_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 130, 961, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.ado_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ado_name_label.setStyleSheet("#ado_name_label{\n"
                                          "background-color:rgba(18,19,25,255);\n"
                                          "color:rgba(253,253,254,255);\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 8pt \"Russo One\";\n"
                                          "}")
        self.ado_name_label.setObjectName("ado_name_label")
        self.gridLayout.addWidget(self.ado_name_label, 1, 0, 1, 1)
        self.mc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_label.sizePolicy().hasHeightForWidth())
        self.mc_label.setSizePolicy(sizePolicy)
        self.mc_label.setMinimumSize(QtCore.QSize(200, 200))
        self.mc_label.setMaximumSize(QtCore.QSize(200, 200))
        self.mc_label.setStyleSheet("#mc_label{\n"
                                    "border-image:url(\":/res/image/res/image/mc.jpg\");\n"
                                    "}")
        self.mc_label.setText("")
        self.mc_label.setObjectName("mc_label")
        self.gridLayout.addWidget(self.mc_label, 0, 1, 1, 1)
        self.ado_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ado_label.sizePolicy().hasHeightForWidth())
        self.ado_label.setSizePolicy(sizePolicy)
        self.ado_label.setMinimumSize(QtCore.QSize(200, 200))
        self.ado_label.setMaximumSize(QtCore.QSize(200, 200))
        self.ado_label.setStyleSheet("#ado_label{\n"
                                     "border-image:url(\":/res/image/res/image/ado.jpg\");\n"
                                     "}")
        self.ado_label.setText("")
        self.ado_label.setObjectName("ado_label")
        self.gridLayout.addWidget(self.ado_label, 0, 0, 1, 1)
        self.ckw_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckw_label.sizePolicy().hasHeightForWidth())
        self.ckw_label.setSizePolicy(sizePolicy)
        self.ckw_label.setMaximumSize(QtCore.QSize(200, 200))
        self.ckw_label.setStyleSheet("#ckw_label{\n"
                                     "border-image:url(\":/res/image/res/image/ckw.jpg\");\n"
                                     "}")
        self.ckw_label.setText("")
        self.ckw_label.setObjectName("ckw_label")
        self.gridLayout.addWidget(self.ckw_label, 0, 2, 1, 1)
        self.mc_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_name_label.setStyleSheet("#mc_name_label{\n"
                                         "background-color:rgba(18,19,25,255);\n"
                                         "color:rgba(253,253,254,255);\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 8pt \"Russo One\";\n"
                                         "}")
        self.mc_name_label.setObjectName("mc_name_label")
        self.gridLayout.addWidget(self.mc_name_label, 1, 1, 1, 1)
        self.ckw_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ckw_name_label.setStyleSheet("#ckw_name_label{\n"
                                          "background-color:rgba(18,19,25,255);\n"
                                          "color:rgba(253,253,254,255);\n"
                                          "border-radius:5px;\n"
                                          "text-align:left;\n"
                                          "font: 8pt \"Russo One\";\n"
                                          "}")
        self.ckw_name_label.setObjectName("ckw_name_label")
        self.gridLayout.addWidget(self.ckw_name_label, 1, 2, 1, 1)
        self.dp_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dp_name_label.setStyleSheet("#dp_name_label{\n"
                                         "background-color:rgba(18,19,25,255);\n"
                                         "color:rgba(253,253,254,255);\n"
                                         "border-radius:5px;\n"
                                         "text-align:left;\n"
                                         "font: 8pt \"Russo One\";\n"
                                         "}")
        self.dp_name_label.setObjectName("dp_name_label")
        self.gridLayout.addWidget(self.dp_name_label, 1, 3, 1, 1)
        self.dp_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dp_label.setMaximumSize(QtCore.QSize(200, 200))
        self.dp_label.setStyleSheet("#dp_label{\n"
                                    "border-image:url(\":/res/image/res/image/dp.jpg\");\n"
                                    "}")
        self.dp_label.setText("")
        self.dp_label.setObjectName("dp_label")
        self.gridLayout.addWidget(self.dp_label, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setRowStretch(0, 7)
        self.stack.addWidget(self.indexpage)
        page2 = QtWidgets.QWidget()
        self.playlistpage = playlist_page.Ui_playlist_page()
        self.playlistpage.setupUi(page2,self.mp)
        self.stack.addWidget(page2)
        self.retranslateUi(Form)
        self.thread = Qthread.ThreadTask(self.mp)
        self.thread.trigger.connect(self.update_time_label)
        self.thread.qthread_signal.connect(self.update_process_bar)
        self.music_handle.finished.connect(self.autochangesong)
        self.stack.setCurrentIndex(0)
        self.playlistpage.listWidget.doubleClicked.connect(self.select_song)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def select_song(self):
        index = self.playlistpage.listWidget.currentRow()
        if index != self.mp.current_index:
            self.mp.select_song(index)
            self.play_button.setChecked(True)
            self.mp.play_song()
            self.thread.start()
            self.update_info()
        else:
            self.play_button.click()

    def playevent(self):
            if self.play_button.isChecked():
                if not self.mp.ispaued:
                    self.mp.play_song()
                    self.thread.start()
                    self.update_info()
                    self.music_handle.playing()
                else:
                    self.mp.unpause()
                    self.thread.start()
                    self.music_handle.playing()
            else:
                self.mp.pause()


    def update_info(self):
        self.music_end_label.setText(self.mp.playtime())
        self.current_song_name_label.setText(str(self.mp.currentmusic().title))
        self.current_song_artist_label.setText(str(self.mp.currentmusic().author))
        self.music_bar.setMaximum(int(self.mp.currentmusic().totaltime))
        myPixmap = QtGui.QPixmap(self.mp.currentmusic().img)
        myScaledPixmap = myPixmap.scaled(71, 51)
        self.current_song_icon_label.setPixmap(myScaledPixmap)

    def nextsong_event(self):
        self.mp.next()
        self.update_info()
        self.thread.start()
        if not self.play_button.isChecked():
            self.play_button.click()

    def presong_event(self):
        self.mp.pre()
        self.update_info()
        self.thread.start()
        if not self.play_button.isChecked():
            self.play_button.click()


    def switchpage(self,index):
        if index < self.stack.count():
            self.stack.setCurrentIndex(index)


    def update_time_label(self, value):
            self.music_start_label.setText(value)

    def update_process_bar(self,value):
        self.music_bar.setValue(value)

    def autochangesong(self,value):
        if value == "Finished":
            self.nextsong_event()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.app_label.setText(_translate("Form", "App"))
        self.explore_button.setText(_translate("Form", "Explore"))
        self.suggest_button.setText(_translate("Form", "Suggest"))
        self.tc_button.setText(_translate("Form", "Top Charts"))
        self.ns_button.setText(_translate("Form", "New Stuff"))
        self.person_label.setText(_translate("Form", "Personal"))
        self.favorite_button.setText(_translate("Form", "Favorite"))
        self.Albums_button.setText(_translate("Form", "Albums"))
        self.playlist_button.setText(_translate("Form", "Playlists"))
        self.gendres_button.setText(_translate("Form", "Genders"))
        self.music_start_label.setText(_translate("Form", "00:00"))
        self.music_end_label.setText(_translate("Form", "00:00"))
        self.current_song_icon_label.setText(_translate("Form", "TextLabel"))
        self.search_lineedit.setPlaceholderText(_translate("Form", "Search music"))
        self.explore_new_label.setText(_translate("Form", "Explore new"))
        self.popular_label.setText(_translate("Form", "Popular"))
        self.mood_label.setText(_translate("Form", "Mood"))
        self.ado_name_label.setText(_translate("Form", "Ado"))
        self.mc_name_label.setText(_translate("Form", "萬能青年旅店"))
        self.ckw_name_label.setText(_translate("Form", "張國榮"))
        self.dp_name_label.setText(_translate("Form", "Dark Punk"))


import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    _id = QtGui.QFontDatabase.addApplicationFont("res/font/RussoOne-Regular.ttf")
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
