# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playlist_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import custom_item


class Ui_playlist_page(object):
    indexsignal = QtCore.pyqtSignal(int)

    def setupUi(self, playlist_page,mp):
        playlist_page.setObjectName("playlist_page")
        playlist_page.resize(1072, 681)
        playlist_page.setStyleSheet("")
        self.mp = mp
        self.playlist = self.mp.playlist()
        self.frame = QtWidgets.QFrame(playlist_page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1071, 681))
        self.frame.setStyleSheet("#frame{\n"
"background-color:rgba(20,21,28,255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1071, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlist_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.playlist_label.setStyleSheet("#playlist_label{\n"
"background-color:rgba(18,19,25,255);\n"
"color:rgba(253,253,254,255);\n"
"border-radius:5px;\n"
"text-align:left;\n"
"font: 15pt \"Russo One\";\n"
"margin-top: 50px;\n"
"}")
        self.playlist_label.setObjectName("playlist_label")
        self.verticalLayout.addWidget(self.playlist_label)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        for i in self.playlist:
            cust_item = custom_item.QCustomQWidget()
            if i.title != None:
                cust_item.setTextUp(i.title)
            else:
                resu = self.findname_title(i.path)
                cust_item.setTextUp(resu[1])
            cust_item.setTextDown(i.author)
            cust_item.setIcon(i.img)
            cust_item.settime(i.end_time)
            myQListWidgetItem = QtWidgets.QListWidgetItem(self.listWidget)
            myQListWidgetItem.setSizeHint(cust_item.sizeHint())
            self.listWidget.addItem(myQListWidgetItem)
            self.listWidget.setItemWidget(myQListWidgetItem, cust_item)
        self.listWidget.setMinimumSize(1071,592)
        self.listWidget
        self.listWidget.setStyleSheet('''
        background-color:rgba(20,21,28,255);
        border:0px;
        ''')
        self.retranslateUi(playlist_page)
        QtCore.QMetaObject.connectSlotsByName(playlist_page)

    def retranslateUi(self, playlist_page):
        _translate = QtCore.QCoreApplication.translate
        playlist_page.setWindowTitle(_translate("playlist_page", "Form"))
        self.playlist_label.setText(_translate("playlist_page", "Play List"))

    def findname_title(self,path):
        ls = str(path).split("\\")
        return ls[2],ls[3][0:len(ls[3])-4]

    def listwidgetclicked(self):
        print('!!! click {}'.format(self.listWidget.currentRow()))